% build_sgesvj_mex.m
openblas_lib = '/Users/cyae/OpenBLAS/lib';   % OpenBLAS 0.3.29.dev - do NOT use /opt/homebrew/opt/openblas (>=0.3.31 pulls libomp and segfaults MATLAB)
gfortran_lib = '/opt/homebrew/opt/gcc/lib/gcc/current';   % version-independent symlink; the old gcc/15.x paths no longer exist

mex('-v','sgesvj_mex.c', ...
    ['-L' openblas_lib], '-lopenblas', ...
    ['-L' gfortran_lib], '-lgfortran', ...
    ['LDFLAGS=$LDFLAGS -Wl,-rpath,' openblas_lib ' -Wl,-rpath,' gfortran_lib]);
